'use client'

import {
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  X,
  Menu,
  Search,
  ShoppingCart,
  User,
  Heart,
  Star,
  Plus,
  Minus,
  Filter,
  MapPin,
  Phone,
  Mail,
  Facebook,
  Twitter,
  Instagram,
  Youtube,
  Linkedin,
  Store,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Check,
  Edit,
  Trash,
  Settings,
  LogOut,
  Home,
  Grid,
  List,
  Package,
  Clock,
  Calendar,
  DollarSign,
  Share,
  Download,
  Upload,
  ExternalLink,
  Loader,
  Navigation,
  CreditCard,
  Banknote,
  Tag,
  type LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  menu: Menu,
  search: Search,
  cart: ShoppingCart,
  user: User,
  heart: Heart,
  star: Star,
  plus: Plus,
  minus: Minus,
  filter: Filter,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  youtube: Youtube,
  linkedin: Linkedin,
  store: Store,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  check: Check,
  edit: Edit,
  trash: Trash,
  settings: Settings,
  logout: LogOut,
  home: Home,
  grid: Grid,
  list: List,
  package: Package,
  clock: Clock,
  calendar: Calendar,
  dollar: DollarSign,
  share: Share,
  download: Download,
  upload: Upload,
  external: ExternalLink,
  spinner: Loader,
  navigation: Navigation,
  x: X,
  creditCard: CreditCard,
  banknote: Banknote,
  shoppingCart: ShoppingCart,
  tag: Tag,
}
